import { boolean, foreignKey, index, integer, jsonb, pgTable, real, text, timestamp } from "drizzle-orm/pg-core";
import { projects } from "./projects";

export const databases = pgTable(
	"databases",
	{
		id: text().primaryKey(),
		projectId: text("project_id"),
		serverId: text("server_id"),
		name: text().notNull(),
		type: text().notNull(),
		version: text(),
		databaseName: text("database_name").notNull(),
		username: text().notNull(),
		password: text(),
		passwordEncrypted: text("password_encrypted"),
		passwordIv: text("password_iv"),
		passwordTag: text("password_tag"),
		internalHost: text("internal_host").notNull(),
		internalPort: integer("internal_port").notNull(),
		cpuLimit: real("cpu_limit"),
		memoryLimitMb: integer("memory_limit_mb"),
		storageLimitMb: integer("storage_limit_mb"),
		storageUsedMb: integer("storage_used_mb").notNull().default(0),
		publicAccess: boolean("public_access").notNull().default(true),
		allowPublicAccessFromAnywhere: boolean("allow_public_access_from_anywhere").notNull().default(false),
		allowedCidrs: jsonb("allowed_cidrs").notNull().default([]),
		externalPort: integer("external_port"),
		proxyContainerName: text("proxy_container_name"),
		volumeName: text("volume_name").notNull(),
		connectionString: text("connection_string").notNull(),
		status: text().notNull().default("provisioning"),
		containerName: text("container_name"),
		backupEnabled: boolean("backup_enabled").notNull().default(true),
		backupSchedule: text("backup_schedule").notNull().default("0 */6 * * *"),
		backupRetention: integer("backup_retention").notNull().default(7),
		createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
		updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
	},
	(table) => [foreignKey({ columns: [table.projectId], foreignColumns: [projects.id], onDelete: "set null" })],
);

export const backups = pgTable(
	"backups",
	{
		id: text().primaryKey(),
		targetId: text("target_id").notNull(),
		targetType: text("target_type").notNull(),
		engine: text().notNull(),
		filename: text(),
		storageType: text("storage_type").notNull(),
		storagePath: text("storage_path"),
		sizeBytes: integer("size_bytes"),
		isEncrypted: boolean("is_encrypted").notNull().default(false),
		error: text(),
		status: text().notNull().default("pending"),
		createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
		completedAt: timestamp("completed_at", { withTimezone: true }),
	},
	(table) => [
		index("idx_backups_target").on(table.targetId),
		index("idx_backups_created").on(table.createdAt),
		index("idx_backups_status").on(table.status),
	],
);

export const backupStorageSettings = pgTable("backup_storage_settings", {
	id: text().primaryKey(),
	type: text().notNull().default("local"),
	path: text().default("/data/backups"),
	s3Endpoint: text("s3_endpoint"),
	s3AccessKeyId: text("s3_access_key_id"),
	s3SecretAccessKeyEncrypted: text("s3_secret_access_key_encrypted"),
	s3SecretAccessKeyIv: text("s3_secret_access_key_iv"),
	s3SecretAccessKeyTag: text("s3_secret_access_key_tag"),
	s3Bucket: text("s3_bucket"),
	s3Region: text("s3_region").default("auto"),
	systemBackupSchedule: text("system_backup_schedule").default("0 */6 * * *"),
	systemBackupRetention: integer("system_backup_retention").default(7),
	updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});
